
training of backgammon
(1, 34)
{'value_loss': 0.18739046156406403, 'loss_actor': -0.020811041817069054, 'entropy': 1.311829686164856, 'eval_vs_previous_policy': 1.100000023841858, 'steps': 16384}
{'value_loss': 0.1615632176399231, 'loss_actor': -0.021924560889601707, 'entropy': 1.2766869068145752, 'eval_vs_previous_policy': 1.7000000476837158, 'steps': 32768}
{'value_loss': 0.11891566962003708, 'loss_actor': -0.023382484912872314, 'entropy': 1.2688990831375122, 'eval_vs_previous_policy': 0.800000011920929, 'steps': 49152}
{'value_loss': 0.12077051401138306, 'loss_actor': -0.02189479023218155, 'entropy': 1.2614240646362305, 'eval_vs_previous_policy': -0.800000011920929, 'steps': 65536}
{'value_loss': 0.1075487732887268, 'loss_actor': -0.02351796068251133, 'entropy': 1.2492449283599854, 'eval_vs_previous_policy': 1.3000000715255737, 'steps': 81920}
{'value_loss': 0.12939172983169556, 'loss_actor': -0.023502808064222336, 'entropy': 1.2345272302627563, 'eval_vs_previous_policy': 1.5, 'steps': 98304}
{'value_loss': 0.11014973372220993, 'loss_actor': -0.0231102854013443, 'entropy': 1.2351319789886475, 'eval_vs_previous_policy': 1.600000023841858, 'steps': 114688}
Traceback (most recent call last):
  File "/root/src/pgx/pgx/workspace/backgammon_trainig/ppo.py", line 357, in <module>
    end = time.time()
  File "/root/src/pgx/pgx/workspace/backgammon_trainig/ppo.py", line 320, in train
    log = {
  File "/root/src/pgx/pgx/workspace/backgammon_trainig/ppo.py", line 267, in evaluate
    return cum_return.mean()
  File "/root/.pyenv/versions/3.10.0/lib/python3.10/site-packages/jax/_src/traceback_util.py", line 166, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/root/.pyenv/versions/3.10.0/lib/python3.10/site-packages/jax/_src/api.py", line 1239, in vmap_f
    out_flat = batching.batch(
  File "/root/.pyenv/versions/3.10.0/lib/python3.10/site-packages/jax/_src/linear_util.py", line 188, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/root/src/pgx/pgx/workspace/backgammon_trainig/ppo.py", line 80, in _get
    return x[i]
  File "/root/.pyenv/versions/3.10.0/lib/python3.10/site-packages/jax/_src/numpy/array_methods.py", line 790, in op
    return getattr(self.aval, f"_{name}")(self, *args)
  File "/root/.pyenv/versions/3.10.0/lib/python3.10/site-packages/jax/_src/numpy/lax_numpy.py", line 4077, in _rewriting_take
    if (result := _attempt_rewriting_take_via_slice(arr, idx, mode)) is not None:
  File "/root/.pyenv/versions/3.10.0/lib/python3.10/site-packages/jax/_src/numpy/lax_numpy.py", line 4064, in _attempt_rewriting_take_via_slice
    arr = lax.squeeze(arr, tuple(int_indices))
  File "/root/.pyenv/versions/3.10.0/lib/python3.10/site-packages/jax/_src/lax/lax.py", line 1307, in squeeze
    ndim = np.ndim(array)
  File "<__array_function__ internals>", line 180, in ndim
  File "/root/.pyenv/versions/3.10.0/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 3197, in ndim
    return a.ndim
  File "/root/.pyenv/versions/3.10.0/lib/python3.10/site-packages/jax/_src/core.py", line 679, in __getattr__
    attr = getattr(self.aval, name)
  File "/root/.pyenv/versions/3.10.0/lib/python3.10/site-packages/jax/_src/interpreters/batching.py", line 270, in aval
    aval = raise_to_shaped(core.get_aval(self.val))
  File "/root/.pyenv/versions/3.10.0/lib/python3.10/site-packages/jax/_src/core.py", line 1334, in get_aval
    return concrete_aval(x)
  File "/root/.pyenv/versions/3.10.0/lib/python3.10/site-packages/jax/_src/core.py", line 1323, in concrete_aval
    if handler: return handler(x)
  File "/root/.pyenv/versions/3.10.0/lib/python3.10/site-packages/jax/_src/abstract_arrays.py", line 53, in canonical_concrete_aval
    return ConcreteArray(dtypes.canonicalize_dtype(np.result_type(val)), val,
  File "<__array_function__ internals>", line 180, in result_type
jax._src.traceback_util.UnfilteredStackTrace: TypeError: Cannot interpret 'Array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]], dtype=float32)' as a data type
The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.
--------------------
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/root/src/pgx/pgx/workspace/backgammon_trainig/ppo.py", line 357, in <module>
    end = time.time()
  File "/root/src/pgx/pgx/workspace/backgammon_trainig/ppo.py", line 320, in train
    log = {
  File "/root/src/pgx/pgx/workspace/backgammon_trainig/ppo.py", line 267, in evaluate
    return cum_return.mean()
  File "/root/src/pgx/pgx/workspace/backgammon_trainig/ppo.py", line 80, in _get
    return x[i]
  File "/root/.pyenv/versions/3.10.0/lib/python3.10/site-packages/jax/_src/numpy/array_methods.py", line 790, in op
    return getattr(self.aval, f"_{name}")(self, *args)
  File "/root/.pyenv/versions/3.10.0/lib/python3.10/site-packages/jax/_src/numpy/lax_numpy.py", line 4077, in _rewriting_take
    if (result := _attempt_rewriting_take_via_slice(arr, idx, mode)) is not None:
  File "/root/.pyenv/versions/3.10.0/lib/python3.10/site-packages/jax/_src/numpy/lax_numpy.py", line 4064, in _attempt_rewriting_take_via_slice
    arr = lax.squeeze(arr, tuple(int_indices))
  File "<__array_function__ internals>", line 180, in ndim
  File "/root/.pyenv/versions/3.10.0/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 3197, in ndim
    return a.ndim
  File "<__array_function__ internals>", line 180, in result_type
TypeError: Cannot interpret 'Array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]], dtype=float32)' as a data type